name: main-push-check

on:
  pull_request:
    branches: ['**']

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make EXTCPP=clang++

